const Products = [
  {
    product_id: 1,
    product_title: "หูฟังไร้สาย Sony WF-1000XM5",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 100,
    product_color_2_name: "เงิน",
    product_color_2_in_stock: 90,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 9990,
    product_description: "หูฟังไร้สายตัดเสียงรบกวนจากทาง Sony ในรุ่น WF-1000XM5 เป็นหูฟังรุ่น Mark 5 โดยตัวหูฟังจะถูกออกแบบมาให้มีขนาดเล็กสวมใส่สบาย และมาพร้อม กับฟังก์ชันการใช้งานต่างๆ ที่โดดเด่น และที่ขาดไม่ได้คือฟังก์ชันการตัดเสียงรบกวนที่ดีที่สุดของทางแบรนด์ Sony\n\nในส่วนของการออกแบบนั้น Sony WF-1000XM5 เป็นหูฟัง In-ear ชนิด True Wireless ตัวบอดี้ของหูฟังถูกออกแบบตามหลักสรีรศาสตร์โดยใช้ข้อมูลจากรูปทรงของหูฟังที่รวบรวมมาตั้งแต่ปี 1982 ให้สามารถสวมใส่ได้อย่างกระชับและสบายหู โดยตัวหูฟังจะที่มีขนาดที่เล็กลงประมาณ 25% และมีน้ำหนักเบาลงประมาณ 20% เมื่อเทียบกับรุ่นก่อนหน้าโดยตัวหูฟังจะมาพร้อมกับสีสันให้เลือกด้วยกันสองสีได้แก่สีดำและสีเงิน",
    product_category: 1,
    category_name: "หูฟัง Truewireless",
    product_brand: 1,
    brand_name: "Sony"
  },
  {
    product_id: 2,
    product_title: "หูฟังไร้สาย Sennheiser Momentum True Wireless 3",
    product_color_1_name: "Black",
    product_color_1_in_stock : 10,
    product_color_2_name : "Graphite",
    product_color_2_in_stock: 9,
    product_color_3_name: "White",
    product_color_3_in_stock: 10,
    product_price: 7800,
    product_description: "น้ำเสียงของ Sennheiser นั้นเป็นที่รู้กันว่าให้โทนเสียงที่ฟังได้ง่ายฟังสบายโดยที่ยังคงให้รายละเอียดเสียงที่ดีเยี่ยมมาแต่ไหนแต่ไรทำให้แฟน ๆ ของทางแบรนด์หลายท่านไม่สามารถมูฟออนจากเสียงของ Sennheiser ได้เลยก็มีครับ \n\nเสียงต่ำ : โดยในย่านเสียงต่ำนั้นเสียงเบสจะมีมวลที่หนาติดนุ่มนิด ๆ แรงปะทะนั้นเรียกได้ว่ามาในระดับปานกลางโดดเด่นในย่าน Mid-Bass มาก ๆ ซึ่งสามารถเข้ากันได้ดีกับแนวเพลงหลาย ๆ แนว โดยเสียงเบสนั้นถูกวางตำแหน่งไว้ค่อนข้างลึกและมีขอบเขตที่ชัดเจนไม่ล้นขึ้นมาชิดกับเสียงนักร้องทำให้เสียงโดยรวมนั้นไม่บวมและถือว่าเป็นเบสที่มีคุณภาพทีเดียวครับ แต่ท่านใดที่ชอบฟังแนว EDM ที่ต้องการความหนักหน่วงมากกว่าความสมูทอาจจะต้องไปเพิ่มเบสในแอปลิเคชันอีกสักหน่อยครับ แต่ถ้าเป็นเพลงสไตล์ Pop, Jazz, R&B ก็ถือว่าเบสนั้นมีมาให้แบบเพียงพอไม่ขาดไม่เกินครับ ",
    product_category: 1,
    category_name: "หูฟัง Truewireless",
    product_brand: 6,
    brand_name: "Sennheiser"
  },
  {
    product_id: 3,
    product_title: "หูฟังไร้สาย Sony WF-1000XM4",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 9,
    product_color_2_name: "เงิน",
    product_color_2_in_stock: 8,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 6990,
    product_description: "เป็นหูฟัง in ear แบบ true wireless ที่เป็นรุ่นที่ 4 แล้วครับ โดยในรุ่นนี้จะออกแบบใหม่ทั้งในส่วนของตัวหูฟังและเคสสำหรับพกพา พร้อมฟังก์ชั่นใหม่ๆที่น่าสนใจหลายอย่างด้วยกัน\n\nในส่วนของการออกแบบนั้น Sony WF-1000XM4 นั้นเป็นหูฟัง in ear ชนิด true wireless ที่จะแยกออกจากกันอย่างอิสระ ไม่มีสายเชื่อมต่อใดๆครับ ตัวบอดี้ใช้วัสดุทำจากพลาสติกลักษณะด้าน ทำความสะอาดง่าย ออกแบบตามหลักสรีรศาสตร์ที่จะสวมใส่ได้อย่างพอดี ไม่รู้สึกเจ็บ และกระชับมากๆครับ ที่ตัวหูฟังนั้นจะไม่มีปุ่มกดใดๆ โดยจะควบคุมผ่านระบบสัมผัสที่หูฟังทั้งสองข้าง มาพร้อมกับเคสสำหรับพกพาและชาร์จแบตเตอรี่ในตัว ซึ่งตัวเคสจะรองรับการชาร์จแบตเตอรี่แบบไร้สาย",
    product_category: 1,
    category_name: "หูฟัง Truewireless",
    product_brand: 1,
    brand_name: "Sony"
  },
  {
    product_id: 4,
    product_title: "หูฟังไร้สาย Marshall Minor III",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 15,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 4310,
    product_description: "Meet Minor III and experience Marshall signature sound without the clutter. Enjoy 25 hours of wireless playtime and the freedom of listening without wires with none of the compromise on sound. These wireless earbuds do all the heavy lifting for you, so all you have to do is grab your music and go.",
    product_category: 1,
    category_name: "หูฟัง Truewireless",
    product_brand: 3,
    brand_name: "Marshall"
  },
  {
    product_id: 5,
    product_title: "หูฟังไร้สาย Bose QuietComfort Earbuds II",
    product_color_1_name: "Triple Black",
    product_color_1_in_stock: 9,
    product_color_2_name: "Midnight Blue",
    product_color_2_in_stock: 9,
    product_color_3_name: "Soapstone",
    product_color_3_in_stock: 3,
    product_price: 10990,
    product_description: "เป็นหูฟัง earbuds ชนิด true wireless ที่มีจุดเด่นอยู่ที่การตัดเสียงรบกวนที่ยอดเยี่ยม\n\nในส่วนของการออกแบบนั้น Bose QuietComfort Earbuds II จะมีดีไซน์ที่คล้ายกับรุ่นแรก โดยที่ด้านหน้าจะเรียวเล็กกว่า พร้อมกับพื้นผิวที่มีความขรุขระ ช่วยให้แตะสั่งงานได้ง่ายยิ่งขึ้น โดยตัวหูฟังจะเป็นลักษณะ earbuds และใช้ stability bands ช่วยยึดไม่ให้ตัวหูฟังหลุดร่วง โดยภายในกล่องจะมีตัวจุกและ stability bands ให้เลือกเปลี่ยนเพื่อความพอดีสูงสุด มาพร้อมกับเคสสำหรับจัดเก็บและชาร์จแบตเตอรี่ที่จะเป็นสีเดียวกันกับตัวหูฟังอีกด้วย",
    product_category: 1,
    category_name: "หูฟัง Truewireless",
    product_brand: 4,
    brand_name: "Bose"
  },
  {
    product_id: 6,
    product_title: "หูฟัง Moondrop Shiro-Yuki",
    product_color_1_name: "White",
    product_color_1_in_stock: 50,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 490,
    product_description: "เป็นหูฟัง Earbud รุ่นล่าสุด และ เป็นรุ่นเริ่มต้นของ Moondrop ในเวลานี้ โดยใช้ Dynamic Driver เป็นตัวขับเสียง บอดี้ใสเคลียเห็นแผงวงจรภายใน สายของหูฟังเป็นทองแดงล้วนความยาว 1.2 M. หุ้มด้วยพลาสติกใส เพิ่มความแข็งแรงให้กับสายหูฟังได้ดีมากๆ ",
    product_category: 2,
    category_name: "หูฟัง Eadbud",
    product_brand: 7,
    brand_name: "Moondrop"
  },
  {
    product_id: 7,
    product_title: "หูฟัง Yuin Pk2",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 3,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 1790,
    product_description: "หูฟังสุดยอดเอียร์บัดจากแบรนด์ Yuin ที่เป็นดาวค้างฟ้าไม่มีวันล่วงหล่นเพราะผ่านไปนานแค่ไหนก็ยังมีแต่คนถามถึงอยู่ตลอด จนขายดิบขายดีเป็นเทน้ำเทท่ากันไปแล้วไม่รู้กี่รอบ วันนี้มาต่อกันยาวๆไปเลยละกันครับกับรุ่น PK2 ที่ถือว่าได้รับความนิยมมากที่สุดในซีรี่ย์พีเคนี้แล้ว",
    product_category: 2,
    category_name: "หูฟัง Eadbud",
    product_brand: 8,
    brand_name: "Yuin"
  },
  {
    product_id: 8,
    product_title: "หูฟัง Moondrop VX Classic",
    product_color_1_name: "เงิน",
    product_color_1_in_stock: 7,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 2490,
    product_description: "หูฟังเอียร์บัด ถือเป็นหูฟังที่ให้การสวมสบายเมื่อใส่เป็นเวลานาน รู้สึกสบายไม่อึดอัดหรือเจ็บช่องหูครับ ตัวบอดีของ VX Classic นั้นทำจากทองเหลือง ขึ้นรูปเเน่นหนาเเข็งเเรง ชุบโครเมียม เนื้อผิวเนียนเรียบ สวยงามน้ำหนักเบา ทำให้สวมใส่สบายเเละได้นานไม่ล้าหู\n\nส่วนตัวสายเป็นทองเเดง OFC ลักษณะของตัวสายทรงกลมหนามีความยืดหยุ่นที่ดีครับ หัวเเจ็คเรียงเล็กใช้งานคล่องตัวเเถมยังเข้าหัวไว้เเน่นหนาเเข็งเเรงอีกด้วยครับ ด้านอุปกรณ์ที่เสริมมาไว้ให้ใช้งานก็มีทั้งซองผ้าเเละ ฟองน้ำเเบบครบถ้วน",
    product_category: 2,
    category_name: "หูฟัง Eadbud",
    product_brand: 7,
    brand_name: "Moondrop"
  },
  {
    product_id: 9,
    product_title: "หูฟัง Yuin Pk3",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 8,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 1190,
    product_description: "ซึ่งรุ่นนี้เป็นรุ่นฮิตสามัญประจำบ้าน ด้วยบอดี้ที่มีขนาดเล็ก น้ำหนักเบา มีขนาดไม่ใหญ่มากทำให้สวมใส่ง่ายมากๆ\n\nสำหรับ Yuin PK3 จะมาในแพคเกจที่เรียกได้ว่าเบสิคมากๆครับ เพราะต้องการประหยัดต้นทุนในส่วนที่ไม่ค่อยจำเป็นแล้วมาเน้นในเรื่องคุณภาพเสียงนั่นเอง ตัวหูฟังนั้นจะดูคล้ายกับหูฟังราคาถูกทั่วๆไป จะมีเพียงสิ่งเดียวที่ทำให้รู้ว่าเป็นหูฟังจากทาง Yuin ก็คือลายสกรีนยี่ห้อ Yuin พร้อมทั้งชื่อรุ่นที่บริเวณก้านนั่นเอง",
    product_category: 2,
    category_name: "หูฟัง Eadbud",
    product_brand: 8,
    brand_name: "Yuin"
  },
  {
    product_id: 10,
    product_title: "หูฟังไร้สาย Sony WH-1000XM5",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 100,
    product_color_2_name: "เงิน",
    product_color_2_in_stock: 50,
    product_color_3_name: "ฟ้า",
    product_color_3_in_stock: 30,
    product_price: 12002,
    product_description: "เทคโนโลยี Noise Cancelling ที่ดีที่สุดในโลกจาก SONY ที่ควบคุมโดยชิป SONY QN1 อันชาญฉลาด ประมวลผลและตัดเสียงรบกวนได้อย่างมีประสิทธิภาพ เงียบอย่างเป็นธรรมชาติ ไม่รู้สึกอึดอัด ให้คุณโฟกัสกับเสียงเพลงของคุณได้เสมือนอยู่ในโลกส่วนตัว เปิดประสบการณ์การฟังแบบ Noise Cancelling ไปอีกระดับ",
    product_category: 3,
    category_name: "หูฟัง Full Size",
    product_brand: 1,
    brand_name: "Sony"
  },
  {
    product_id: 11,
    product_title: "หูฟังไร้สาย Bose QuietComfort 45",
    product_color_1_name: "Black",
    product_color_1_in_stock: 8,
    product_color_2_name: "White Smoke",
    product_color_2_in_stock: 15,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 11900,
    product_description: "หูฟังไร้สายจากทาง Bose ในรุ่น QuietComfort 45 นั้นเป็นหูฟังไร้สายที่มาพร้อมกับระบบตัดเสียงรบกวน Active noise cancelling พร้อมดีไซน์แบบคลาสสิคและการควบคุมการใช้งานแบบกดปุ่ม\n\nในส่วนของการออกแบบนั้น Bose QuietComfort 45 จะเป็นหูฟัง full size ชนิดไร้สาย ตัวหูฟังจะมี ear cup ขนาดใหญ่ เมื่อสวมใส่จะครอบไปทั้งใบหู โดยฟองน้ำจะเป็น memory foam ที่มีความนุ่มนวล หุ้มด้วยหนังเทียมที่ช่วยกันเสียงรบกวนจากภายนอกได้ดี ส่วนที่ด้านซ้ายจะมีสวิตซ์เปิด-ปิด ส่วนปุ่มควบคุมต่างๆจะอยู่ที่ด้านขวา สามารถกดได้อย่างสะดวก โดยภายในกล่องจะมีเคสสำหรับพกพา และสาย USB สำหรับชาร์จแบตเตอรี่มาให้ด้วย",
    product_category: 3,
    category_name: "หูฟัง Full Size",
    product_brand: 4,
    brand_name: "Bose"
  },
  {
    product_id: 12,
    product_title: "หูฟังไร้สาย Audio Technica ATH-M50xBT2",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 5,
    product_color_2_name: "ส้ม",
    product_color_2_in_stock: 9,
    product_color_3_name: "Deep Sea",
    product_color_3_in_stock: 3,
    product_price: 7960,
    product_description: "หูฟังจากทาง Audio Technica ในรุ่น ATH-M50xBT2 เป็นหูฟังแบบ full size ชนิดไร้สาย ที่อัปเกรดฟังก์ชันภายในให้ดีขึ้นกว่าเดิมจากเวอร์ชันก่อนหน้า โดยยังคงไว้ด้วยดีไซน์การออกแบบที่เหมือนเดิม และมาพร้อมกับแบตเตอรี่ที่สามารถใช้งานได้นานสูงสุด 50 ชั่วโมงเลยทีเดียว",
    product_category: 3,
    category_name: "หูฟัง Full Size",
    product_brand: 9,
    brand_name: "Audio Technica"
  },
  {
    product_id: 13,
    product_title: "หูฟัง Grado RS2x",
    product_color_1_name: "Brown",
    product_color_1_in_stock: 8,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 22500,
    product_description: "Maple, Meet Hemp\n\nA family favorite, the RS2x has been completely redesigned to bring out the full potential of its maple and hemp wood. The housing s sleeve and ring are made from maple, while a hemp core keeps everything together. We build with wood for its warm and embracing tonal abilities, and the RS2x is an exceptional evolution to the RS2 line.",
    product_category: 3,
    category_name: "หูฟัง Full Size",
    product_brand: 2,
    brand_name: "Grado"
  },
  {
    product_id: 14,
    product_title: "หูฟังเกมมิ่ง Beyerdynamic MMX300",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 10,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 12490,
    product_description: "สำหรับ MMX300 เป็นหูฟังขนาด full size ครอบทั้งใบหู ตัวฟองน้ำหุ้มด้วยผ้าซึ่งมีความนุ่มนวล แถมยังสามารถระบายอากาศได้ดี เหมาะสำหรับใช้งานเป็นเวลานานเพราะว่าไม่กดทับใบหูแม้แต่น้อย มาพร้อมกับไมโครโฟนประสิทธิภาพสูงที่สามารถตัดเสียงรบกวนจากภายนอกได้อย่างดีเยี่ยม ช่วยให้เราสามารถสื่อสารกับเพื่อร่วมทีมได้อย่างคมชัด สามารถหมุนเก็บได้เมื่อไม่ใช้งาน ภายในกล่องจะมีสายมาให้ถึง 2 เส้นให้เลือกใช้งานได้ตามความเหมาะสม และยังมีเคสกันกระแทกสำหรับพกพามาให้อีกด้วย",
    product_category: 4,
    category_name: "หูฟัง Gaming",
    product_brand: 11,
    brand_name: "Beyerdynamic "
  },
  {
    product_id: 15,
    product_title: "หูฟังเกมมิ่ง HyperX Cloud II Wireless",
    product_color_1_name: "ดำ-แดง",
    product_color_1_in_stock: 9,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 4890,
    product_description: "หูฟังเกมมิ่งจากทาง HyperX ในรุ่น Cloud II Wireless เป็นหูฟังเกมมิ่งแบบไร้สายที่เชื่อมต่อผ่าน USB Dongle Wireless 2.4GHz รองรับการใช้งานร่วมกับอุปกรณ์ที่หลากหลายและมาพร้อมแบตเตอรี่ที่สามารถใช้งานได้ทั้งวัน",
    product_category: 4,
    category_name: "หูฟัง Gaming",
    product_brand: 12,
    brand_name: "HyperX"
  },
  {
    product_id: 16,
    product_title: "หูฟังเกมมิ่ง JBL Quantum 810",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 10,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 7493,
    product_description: "หูฟังจากทาง JBL ในรุ่น Quantum 810 เป็นหูฟังเกมมิ่งที่มีจุดเด่นอยู่ที่ระบบตัดเสียงรบกวน Active Noise Cancelling ที่จะตัดเสียงรบกวนที่ไม่จำเป็นออกไปทำให้คุณโฟกัสกับการเล่นเกมได้มากยิ่งขึ้น และยังรองรับการใช้งานไร้สายผ่าน USB Wireless Dongle 2.4GHz และ Bluetooth 5.2 ด้วย",
    product_category: 4,
    category_name: "หูฟัง Gaming",
    product_brand: 5,
    brand_name: "JBL"
  },
  {
    product_id: 17,
    product_title: "หูฟังเกมมิ่ง Steelseries Arctis Nova Pro Wireless",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 3,
    product_color_2_name: "",
    product_color_2_in_stock: 0,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 13500,
    product_description: "หูฟังจากทาง Steelseries ในรุ่น Arctis Nova Pro Wireless เป็นหูฟังเกมมิ่งชนิดไร้สายตัวท็อปของทางแบรนด์ที่มาพร้อมกับฟังก์ชันการใช้งานที่หลากหลายทั้งฟังก์ชันตัดเสียงรบกวน ANC, Transparency Mode หรือ 360 Spatial Audio และยังมาพร้อมกับแบตเตอรี่ที่สามารถใช้งานได้อย่างยาวนานสูงสุดถึง 36 ชั่วโมงอีกด้วย",
    product_category: 4,
    category_name: "หูฟัง Gaming",
    product_brand: 10,
    brand_name: "Steelseries"
  },
  {
    product_id: 18,
    product_title: "ลำโพง Marshall Middleton",
    product_color_1_name: "ดำ",
    product_color_1_in_stock: 10,
    product_color_2_name: "ครีม",
    product_color_2_in_stock: 9,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 12990,
    product_description: "ลำโพงจากทาง Marshall ในรุ่น Middleton เป็นลำโพงพกพารุ่นใหม่ล่าสุดจากทางแบรนด์ โดยในรุ่นนี้จะมีดีไซน์การออกแบบที่คล้ายๆกับรุ่นEmberton II แต่จะมีขนาดที่ใหญ่กว่า โดยจะมาพร้อมกับฟังก์ชัน Stack Mode และแบตเตอรี่ที่สามารถใช้งานได้นานสูงสุด 20 ชั่วโมง",
    product_category: 5,
    category_name: "ลำโพงพกพา",
    product_brand: 3,
    brand_name: "Marshall"
  },
  {
    product_id: 19,
    product_title: "ลำโพง Marshall Willen",
    product_color_1_name: "Black and Brass",
    product_color_1_in_stock: 10,
    product_color_2_name: "Cream",
    product_color_2_in_stock: 9,
    product_color_3_name: "",
    product_color_3_in_stock: 0,
    product_price: 3990,
    product_description: "ลำโพงจากทาง Marshall ในรุ่น Willen เป็นลำโพงพกพารุ่นน้องเล็กสุดของทางแบรนด์ครับ โดยในรุ่นนี้จะมาพร้อมกับสายรัดที่ด้านหลังตัวเครื่อง สำหรับรัดเข้ากับกระเป๋าหรือสิ่งของอื่นๆก็ได้ พร้อมแบตเตอรี่ที่ใช้งานได้ยาวนานสูงสุด 15 ชั่วโมง",
    product_category: 5,
    category_name: "ลำโพงพกพา",
    product_brand: 3,
    brand_name: "Marshall"
  },
  {
    product_id: 20,
    product_title: "ลำโพง JBL Flip 5",
    product_color_1_name: "Black",
    product_color_1_in_stock: 10,
    product_color_2_name: "Blue",
    product_color_2_in_stock: 9,
    product_color_3_name: "Gray",
    product_color_3_in_stock: 8,
    product_price: 4390,
    product_description: "สำหรับลำโพง JBL Flip 5 นั้นภายนอกจะมีความใกล้เคียงกับรุ่นก่อนหน้าครับ จุดที่แตกต่างก็คือในรุ่นนี้จะไม่มีฝาปิดช่อง USB แล้ว โดยจะเปลี่ยนไปใช้ USB-C ที่เสียบได้สองด้าน ช่วยเพิ่มความสะดวกครับ ส่วนช่อง AUX 3.5mm ที่เป็น in put นั้นถูกตัดออกไปเลย จึงทำให้ในรุ่นนี้จะต้องใช้งานผ่านการเชื่อมต่อ Bluetooth เท่านั้นครับ ตัวลำโพงเลือกใช้วัสดุเป็นพลาสติกที่ผ่านการ rubberize ช่วยให้จับได้อย่างถนัดมือ ส่วนตะแกรงลำโพงจะหุ้มด้วยผ้าที่ทำหน้าที่ไม่ให้น้ำซึมผ่านได้ครับ ปุ่มควบคุมต่างๆทั้ง เล่น-หยุด, ปรับระดับเสียง และปุ่ม Link ลำโพงหลายตัวเข้าด้วยกันครับ ภายในกล่องจะมาพร้อมกับสาย USB-C สำหรับชาร์จแบตเตอรี่",
    product_category: 5,
    category_name: "ลำโพงพกพา",
    product_brand: 5,
    brand_name: "JBL"
  },
];

export default Products;
